services:
  tftp:
    container_name: tftp-server
    image: kaczmar2/tftp-hpa-alpine
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      # - TFTP_ARGS=${TFTP_ARGS:-}  # Optional: Override default TFTP arguments (uncomment to customize)
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
      - /etc/localtime:/etc/localtime:ro
